BaseUrl= "http://onori.github.io/"
LanguageCode= "ja"
Title= "MAN.IN.BLOG"
paginate = 5
theme = "casper"
DisqusShortname = "onori"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "マネージャー業務の日々 コード書くことが少なくなってる。最近はLaravelとElixir（言語のほう）に興味津々。"
  cover = "images/footer_lodyas.png"
  author = "onori"
  authorlocation = "Tokyo, Japan"
  authorwebsite = ""
  bio= "Profile"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "onori"
  # twitterName = "onori"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
